import type { FieldConfiguration } from "@/lib/validators/settings-schema";

/**
 * Default canvas field configurations
 * Extracted from prompts.ts Field-Specific Extraction Rules
 *
 * These fields are seeded into settings when a user first sets up their account
 * Users can then customize, enable/disable, or reorder these fields
 */
export const DEFAULT_CANVAS_FIELDS: FieldConfiguration[] = [
// === CORE FIELDS (Always Required) ===
  {
    id: "title",
    name: "Title",
    fieldKey: "title",
    type: "default",
    category: "core",
    enabled: true,
    includeInGeneration: true,
    order: 0,
    valueType: "string",
    instructions: "Generate a clear, concise title that captures the essence of the business problem or initiative",
    isRequired: true,
    supportsDiagram: false,
    displayStyle: "auto",
    description: "The canvas title - cannot be disabled",
  },
  {
    id: "problemStatement",
    name: "Problem Statement",
    fieldKey: "problemStatement",
    type: "default",
    category: "core",
    enabled: true,
    includeInGeneration: true,
    order: 1,
    valueType: "string",
    instructions: "Extract metrics and business impact from documents; include exact numbers mentioned",
    examples: '"Customer churn rate increased from 5% to 12% over 6 months, resulting in $2M revenue loss"',
    isRequired: true,
    supportsDiagram: false,
    displayStyle: "auto",
    description: "The core business problem - cannot be disabled",
  },
  {
    id: "solutionRecommendation",
    name: "Solution Recommendation",
    fieldKey: "solutionRecommendation",
    type: "default",
    category: "core",
    enabled: true,
    includeInGeneration: true,
    order: 2,
    valueType: "object",
    instructions: "Base recommendations on capabilities and approaches mentioned in documents; add strategic depth with specific actions prioritized by impact",
    isRequired: false,
    supportsDiagram: true,
    displayStyle: "auto",
    description: "Recommended solution with prioritized actions",
  },

  // === PLANNING FIELDS ===
  {
    id: "objectives",
    name: "Objectives",
    fieldKey: "objectives",
    type: "default",
    category: "planning",
    enabled: true,
    includeInGeneration: true,
    order: 3,
    valueType: "array",
    instructions: "Extract stated goals and targets EXACTLY as specified in documents; cite document evidence",
    examples: '["Reduce customer acquisition cost by 30%", "Improve user retention to 85%", "Launch MVP in Q2 2025"]',
    negativePrompt: "Do NOT fabricate specific percentage targets without document evidence",
    supportsDiagram: false,
    displayStyle: "bullets",
    isRequired: false,
    description: "Business objectives and goals",
  },
  {
    id: "okrs",
    name: "OKRs",
    fieldKey: "okrs",
    type: "default",
    category: "planning",
    enabled: false,
    includeInGeneration: false,
    order: 4,
    valueType: "array",
    instructions: "Convert objectives into measurable OKRs (Objectives and Key Results); each objective should have 3-4 key results with specific, measurable targets",
    examples: '[{"type": "objective", "title": "Improve user engagement", "description": "..."}, {"type": "key-result", "parentId": "...", "title": "Increase DAU to 100K"}]',
    isRequired: false,
    supportsDiagram: false,
    displayStyle: "auto",
    description: "Objectives and Key Results framework",
  },
  {
    id: "kpis",
    name: "KPIs",
    fieldKey: "kpis",
    type: "default",
    category: "planning",
    enabled: true,
    includeInGeneration: true,
    order: 5,
    valueType: "array",
    instructions: "Look for numerical targets (e.g., 'conversion: 2.1% → 4.5%'); extract ALL metrics mentioned across documents",
    examples: '["Monthly Active Users: 50K → 100K", "Conversion Rate: 2.1% → 4.5%", "Customer Satisfaction Score: 3.8 → 4.5"]',
    negativePrompt: "Do NOT use industry averages - only document-based specific targets",
    isRequired: false,
    supportsDiagram: false,
    displayStyle: "bullets",
    description: "Key Performance Indicators with current and target values",
  },
  {
    id: "successCriteria",
    name: "Success Criteria",
    fieldKey: "successCriteria",
    type: "default",
    category: "planning",
    enabled: false,
    includeInGeneration: false,
    order: 6,
    valueType: "array",
    instructions: "Define specific, measurable criteria that indicate project success based on objectives and KPIs",
    examples: '[{"metric": "User Adoption Rate", "target": "70% within 3 months", "measurement": "Monthly active users / total signups"}]',
    isRequired: false,
    supportsDiagram: false,
    displayStyle: "auto",
    description: "Measurable success criteria",
  },
  {
    id: "urgency",
    name: "Urgency",
    fieldKey: "urgency",
    type: "default",
    category: "planning",
    enabled: true,
    includeInGeneration: true,
    order: 7,
    valueType: "string",
    instructions: "Base on revenue impact, competitive threats, or deadlines mentioned in documents",
    examples: '"high" or "critical" with justification',
    isRequired: false,
    supportsDiagram: false,
    displayStyle: "auto",
    description: "Project urgency level (low/medium/high/critical)",
  },
  {
    id: "timelines",
    name: "Timelines",
    fieldKey: "timelines",
    type: "default",
    category: "planning",
    enabled: true,
    includeInGeneration: true,
    order: 8,
    valueType: "object",
    instructions: "Extract specific dates, quarters, milestones from documents; use document-based timelines over generic estimates",
    examples: '{"start": "2025-01-01", "end": "2025-06-30", "milestones": [{"name": "MVP Launch", "date": "2025-03-15"}]}',
    negativePrompt: "Do NOT fabricate specific dates without document evidence",
    isRequired: false,
    supportsDiagram: true,
    displayStyle: "auto",
    description: "Project timeline with milestones",
  },

  // === TECHNICAL FIELDS ===
  {
    id: "keyFeatures",
    name: "Key Features",
    fieldKey: "keyFeatures",
    type: "default",
    category: "technical",
    enabled: true,
    includeInGeneration: true,
    order: 9,
    valueType: "array",
    instructions: "Extract specific capabilities, technologies, and features mentioned; note vendor names if specified",
    examples: '["Real-time inventory sync", "AI-powered recommendations", "Multi-channel integration"]',
    supportsDiagram: false,
    displayStyle: "bullets",
    isRequired: false,
    description: "Core features and capabilities",
  },
  {
    id: "dependencies",
    name: "Dependencies",
    fieldKey: "dependencies",
    type: "default",
    category: "technical",
    enabled: true,
    includeInGeneration: true,
    order: 10,
    valueType: "array",
    instructions: "Extract named systems, platforms, and vendors from documents (e.g., 'Salesforce Customer 360', 'Google Cloud Platform')",
    examples: '["Salesforce CRM integration", "Payment gateway (Stripe)", "AWS infrastructure"]',
    negativePrompt: "Do NOT fabricate technology stacks without evidence",
    isRequired: false,
    supportsDiagram: true,
    displayStyle: "bullets",
    description: "External systems and platform dependencies",
  },
  {
    id: "dataDependencies",
    name: "Data Dependencies",
    fieldKey: "dataDependencies",
    type: "default",
    category: "technical",
    enabled: true,
    includeInGeneration: true,
    order: 11,
    valueType: "array",
    instructions: "Extract specific data sources, APIs, and integration points mentioned",
    examples: '["Customer database (PostgreSQL)", "Product catalog API", "Analytics data warehouse"]',
    isRequired: false,
    supportsDiagram: false,
    displayStyle: "bullets",
    description: "Data sources and integrations required",
  },
  {
    id: "technicalArchitecture",
    name: "Technical Architecture",
    fieldKey: "technicalArchitecture",
    type: "default",
    category: "technical",
    enabled: false,
    includeInGeneration: false,
    order: 12,
    valueType: "array",
    instructions: "Extract mentioned technologies, platforms, and architectural patterns",
    examples: '[{"layer": "Frontend", "components": ["React", "Next.js"], "description": "Server-side rendered SPA"}]',
    isRequired: false,
    supportsDiagram: true,
    displayStyle: "auto",
    description: "System architecture and technology stack",
  },
  {
    id: "securityCompliance",
    name: "Security & Compliance",
    fieldKey: "securityCompliance",
    type: "default",
    category: "technical",
    enabled: false,
    includeInGeneration: false,
    order: 13,
    valueType: "array",
    instructions: "Extract security requirements, compliance standards, and data privacy needs",
    examples: '["GDPR compliance", "SOC 2 Type II certification", "End-to-end encryption"]',
    isRequired: false,
    supportsDiagram: false,
    displayStyle: "bullets",
    description: "Security and compliance requirements",
  },

  // === FINANCIAL FIELDS ===
  {
    id: "budgetResources",
    name: "Budget & Resources",
    fieldKey: "budgetResources",
    type: "default",
    category: "financial",
    enabled: false,
    includeInGeneration: false,
    order: 14,
    valueType: "object",
    instructions: "Extract EXACT budget numbers, investment allocations, and cost breakdowns; NEVER estimate when data exists",
    examples: '{"totalEstimate": "$500K", "breakdown": [{"category": "Development", "amount": "$300K"}], "fteRequirements": "5 engineers, 2 designers"}',
    negativePrompt: "Do NOT estimate budgets without explicit document data",
    supportsDiagram: false,
    displayStyle: "auto",
    isRequired: false,
    description: "Budget breakdown and resource requirements",
  },
  {
    id: "roiAnalysis",
    name: "ROI Analysis",
    fieldKey: "roiAnalysis",
    type: "default",
    category: "financial",
    enabled: false,
    includeInGeneration: false,
    order: 15,
    valueType: "object",
    instructions: "Calculate return on investment, payback period, and financial justification based on stated benefits and costs",
    examples: '{"expectedReturn": "$2M annual savings", "paybackPeriod": "18 months", "costBenefit": "3:1 ratio"}',
    isRequired: false,
    supportsDiagram: false,
    displayStyle: "auto",
    description: "Return on investment metrics",
  },

  // === RISK & STAKEHOLDERS ===
  {
    id: "risks",
    name: "Risks",
    fieldKey: "risks",
    type: "default",
    category: "risk_stakeholders",
    enabled: true,
    includeInGeneration: true,
    order: 16,
    valueType: "array",
    instructions: "Prioritize real issues documented in customer feedback or project documents over generic risks",
    examples: '["Technical: Legacy system migration complexity", "Business: Market competition from X", "Timeline: Dependency on external vendor"]',
    supportsDiagram: false,
    displayStyle: "bullets",
    isRequired: false,
    description: "Project risks and mitigation strategies",
  },
  {
    id: "stakeholderMap",
    name: "Stakeholder Map",
    fieldKey: "stakeholderMap",
    type: "default",
    category: "risk_stakeholders",
    enabled: false,
    includeInGeneration: false,
    order: 17,
    valueType: "array",
    instructions: "Extract named stakeholders, roles, and organizational structure from documents",
    examples: '[{"name": "Sarah Chen", "role": "Product Owner", "influence": "high", "interest": "high", "raciRole": "accountable"}]',
    negativePrompt: "Do NOT fabricate stakeholder names without document evidence",
    isRequired: false,
    supportsDiagram: true,
    displayStyle: "auto",
    description: "Key stakeholders with influence and interest levels",
  },
  {
    id: "changeManagement",
    name: "Change Management",
    fieldKey: "changeManagement",
    type: "default",
    category: "risk_stakeholders",
    enabled: false,
    includeInGeneration: false,
    order: 18,
    valueType: "object",
    instructions: "Identify training needs, communication plans, adoption strategies, and resistance mitigation",
    examples: '{"trainingNeeds": ["End-user training", "Admin workshops"], "communicationPlan": "Weekly updates to leadership", "adoptionStrategy": "Phased rollout by department"}',
    isRequired: false,
    supportsDiagram: false,
    displayStyle: "auto",
    description: "Change management and adoption plan",
  },
  {
    id: "assumptions",
    name: "Assumptions",
    fieldKey: "assumptions",
    type: "default",
    category: "risk_stakeholders",
    enabled: false,
    includeInGeneration: false,
    order: 19,
    valueType: "array",
    instructions: "List key assumptions that the canvas and recommendations are based on",
    examples: '["Users have reliable internet access", "Current infrastructure can handle 2x traffic", "Team has React expertise"]',
    isRequired: false,
    supportsDiagram: false,
    displayStyle: "bullets",
    description: "Project assumptions to validate",
  },
  {
    id: "alignmentLongTerm",
    name: "Strategic Alignment",
    fieldKey: "alignmentLongTerm",
    type: "default",
    category: "risk_stakeholders",
    enabled: true,
    includeInGeneration: true,
    order: 20,
    valueType: "string",
    instructions: "Extract stated business strategy, market positioning, and long-term goals from documents",
    examples: '"Aligns with 2025 digital transformation initiative and strategic goal to become market leader in AI-powered solutions"',
    isRequired: false,
    supportsDiagram: false,
    displayStyle: "auto",
    description: "How this initiative aligns with long-term strategy",
  },
];

/**
 * Get category display name
 */
export function getCategoryDisplayName(category: string): string {
  const names: Record<string, string> = {
    core: "Core",
    planning: "Planning",
    technical: "Technical",
    financial: "Financial",
    risk_stakeholders: "Risk & Stakeholders",
    custom: "Custom",
  };
  return names[category] || category;
}

/**
 * Get category description
 */
export function getCategoryDescription(category: string): string {
  const descriptions: Record<string, string> = {
    core: "Essential fields that define the canvas",
    planning: "Strategic planning and goal-setting",
    technical: "Technology and architecture details",
    financial: "Budget, resources, and ROI",
    risk_stakeholders: "Risk management and stakeholder engagement",
    custom: "User-defined custom fields",
  };
  return descriptions[category] || "";
}
